/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    Chirp: typeof import('./resources/js/Components/Chirp.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
  }
}
